Repository MTVS-3rd-TODORIAN/TODORIAN_FE, pull requests merged in 2024-09, with the labels that each got.

#4 Dev
  .github/ISSUE_TEMPLATE/✅기능-이슈.md
  .github/ISSUE_TEMPLATE/🚨버그-리포트.md
  .github/pull_request_template.md
Labels: ⚙️ Setting

#7 Feature/todo
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/todo/logo.png
  src/pages/Main.jsx
  src/pages/todo/Todo.jsx
Labels: ✨ Feature

#8 Feature/login
  src/App.jsx
  src/pages/Main.jsx
  src/pages/User/Login.jsx
Labels: ✨ Feature

#9 Dev
  .gitmessage
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/gamePage/baseBall.png
  src/assets/images/gamePage/ladder.png
  src/assets/images/gamePage/soccerBall.png
  src/assets/images/todo/logo.png
  src/pages/Game.jsx
  src/pages/Main.jsx
  src/pages/User/Login.jsx
  src/pages/todo/Todo.jsx
Labels: ✨ Feature, 🔨 Refactor, ⚙️ Setting

#11 [Feat] inventory page 구현
  package.json
  src/App.jsx
  src/pages/inventory/Inventory.jsx
Labels: ✨ Feature

#25 Setting : Tailwind CSS 설치 및 설정
  package-lock.json
  package.json
  postcss.config.js
  src/App.jsx
  src/index.css
  tailwind.config.js
Labels: ⚙️ Setting

#26 [Feat[ Sidebar
  package-lock.json
  package.json
  src/App.jsx
  src/components/Sidebar.jsx
  src/pages/Home.jsx
  src/pages/game/Game.jsx
  src/pages/inventory/Inventory.jsx
  src/pages/todo/Todo.jsx
Labels: ✨ Feature, ⚙️ Setting

#28 [Feat] Sidebar
  package-lock.json
  src/api/auth.js
  src/api/member.js
  src/assets/images/common/profile.png
  src/axios/AxiosInstance.js
  src/components/Sidebar.jsx
Labels: ✨ Feature, 🔨 Refactor

#31 Feature/game
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/components/ui/button.jsx
  src/components/ui/card.jsx
  src/components/ui/input.jsx
  src/components/ui/label.jsx
  src/pages/Main.jsx
  src/pages/game/Game.jsx
  src/pages/game/LadderGame.jsx
Labels: ✨ Feature

#32 [Feat] Farm 페이지 기본 틀 완성
  .gitignore
  src/App.jsx
  src/assets/images/farmPage/arrow.png
  src/assets/images/farmPage/circle.png
  src/assets/images/farmPage/farm1.png
  src/assets/images/farmPage/farm2.png
  src/assets/images/farmPage/farm3.png
  src/assets/images/farmPage/paperAirplane.png
  src/pages/farm/Farm.jsx
  src/pages/guestbook/Guestbook.jsx
Labels: ✨ Feature
